version: 2
jobs:
  release:
    working_directory: /go/src/github.com/kitsuyui/scraper
    docker:
      - image: golang:1.18.1-stretch@sha256:d2bf19df94b36ee7fe4e99d221bf1b0b3b7a077ddfe73c6aae9335f9d9544dbe
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            go get github.com/mitchellh/gox
            go get github.com/tcnksm/ghr
            BUILD_VERSION="$CIRCLE_TAG" ./bin/build.sh
            mkdir /tmp/releases
            mv ./build/scraper_* /tmp/releases
            ghr -u "$CIRCLE_PROJECT_USERNAME" "$CIRCLE_TAG" /tmp/releases
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  build_and_release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+.\d+$/
