version: 2
jobs:
  test:
    working_directory: /workdir
    docker:
      - image: golang:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            ./bin/test.sh
            ./bin/coverage.sh
            bash <(curl -s https://codecov.io/bash)

  release:
    working_directory: /workdir
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            docker create -v /root --name sources tianon/true
            docker cp "$PWD/." sources:/root/
            docker run --rm --volumes-from sources -w /root tcnksm/gox sh -c ./bin/build.sh
            mkdir -p /tmp/artifacts
            docker cp sources:/root/build/ /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  build_and_release:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only: release
