version: 2
jobs:
  test:
    working_directory: /go/src/github.com/kitsuyui/scraper
    docker:
      - image: golang:1.16.0-stretch@sha256:e1148e671c9b08000812c77921895031f463e346a0fdc559dcffc60cf860c4c4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            ./bin/test.sh
            ./bin/coverage.sh
            bash <(curl -s https://codecov.io/bash)

  release:
    working_directory: /go/src/github.com/kitsuyui/scraper
    docker:
      - image: golang:1.16.0-stretch@sha256:e1148e671c9b08000812c77921895031f463e346a0fdc559dcffc60cf860c4c4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            go get github.com/mitchellh/gox
            go get github.com/tcnksm/ghr
            BUILD_VERSION="$CIRCLE_TAG" ./bin/build.sh
            mkdir /tmp/releases
            mv ./build/scraper_* /tmp/releases
            ghr -u "$CIRCLE_PROJECT_USERNAME" "$CIRCLE_TAG" /tmp/releases
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  build_and_release:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+.\d+$/
